Config = Config or {}

Config.Debug = false -- Set to True to enable Debug Prints
Config.MoneyType = 'bank'
Config.RepairMoneyType = 'cash'
Config.UseRadial = false -- Will use qb-radial menu for entering instead of press E
Config.allowGovPlateIndex = false -- Setting this to true will allow all vehicles to purchase gov plate index "Blue on White #3" (only for emergency vehicles otherwise)
maxVehiclePerformanceUpgrades = 0 -- | All Upgrades: 0 | No Upgrades: -1 | Can be -1 to 4

-- ADJUST PRICING
vehicleCustomisationPrices = {
    cosmetics = {price = 400},
    respray = {price = 1000},
    performance = {prices = {0, 3250, 5500, 10450, 15250, 20500, 25000}},
    turbo = {prices = {0, 15000}},
    wheels = {price = 400},
    customwheels = {price = 600},
    wheelsmoke = {price = 400},
    windowtint = {price = 400},
    neonside = {price = 100},
    neoncolours = {price = 500},
    headlights = {price = 100},
    xenoncolours = {price = 500},
    oldlivery = {price = 500},
    plateindex = {price = 1000}
}

-- WINDOW TINTS

vehicleWindowTintOptions = {
    {name = "None", id = 0},
    {name = "Puro Negro", id = 1},
    {name = "Fumaça Negra", id = 2},
    {name = "Fumaça Branca", id = 3}
}

-- HEADLIGHTS

vehicleXenonOptions = {
    xenonColours = {
        {name = "Original",        id = 255},
        {name = "Branco",          id = 0},
        {name = "Azul",            id = 1},
        {name = "Azul Elétrico",   id = 2},
        {name = "Verde Menta",     id = 3},
        {name = "Verde Limão",     id = 4},
        {name = "Amarelo",         id = 5},
        {name = "Dourado",         id = 6},
        {name = "Laranja",         id = 7},
        {name = "Vermelho",        id = 8},
        {name = "Rosa Claro",      id = 9},
        {name = "Rosa Pink",       id = 10},
        {name = "Roxo",            id = 11},
        {name = "Luz Negra",       id = 12}
    }
}

-- WHEELS

vehicleWheelOptions = {
    {category = "Custom Tyres", id = -1, wheelID = 23},
    {category = "Tyre Smoke", id = 20, wheelID = 23},
    {category = "Sport", id = 0, wheelID = 23},
    {category = "Muscle", id = 1, wheelID = 23},
    {category = "Lowrider", id = 2, wheelID = 23},
    {category = "SUV", id = 3, wheelID = 23},
    {category = "Offroad", id = 4, wheelID = 23},
    {category = "Tuner", id = 5, wheelID = 23},
    {category = "Motorcycle", id = 6, wheelID = 23},
    {category = "Highend", id = 7, wheelID = 23},
    {category = "BennysWheel", id = 8, wheelID = 23},
    {category = "BespokeWheel", id = 9, wheelID = 23},
    {category = "Dragster", id = 10, wheelID = 23},
    {category = "Street", id = 11, wheelID = 23},
    {category = "Rally", id = 12, wheelID = 23},
}

-- TIRE SMOKE

vehicleTyreSmokeOptions = {
    { name = "Fumaça Branca", r = 254, g = 254, b = 254},
    { name = "Fumaça Preta", r = 1, g = 1, b = 1},
    { name = "Fumaça Azul", r = 0, g = 150, b = 255},
    { name = "Fumaça Amarela", r = 255, g = 255, b = 50},
    { name = "Fumaça Laranja", r = 255, g = 153, b = 51},
    { name = "Fumaça Vermelha", r = 255, g = 10, b = 10},
    { name = "Fumaça Verde", r = 10, g = 255, b = 10},
    { name = "Fumaça Roxa", r = 153, g = 10, b = 153},
    { name = "Fumaça Rosa", r = 255, g = 102, b = 178},
    { name = "Fumaça Cinza", r = 128, g = 128, b = 128}
}

-- NEONS

vehicleNeonOptions = {
    category = "Neons",
    neonTypes = {
        {name = "Neon Frontal", id = 2},
        {name = "Neon Traseiro", id = 3},
        {name = "Neon Esquerdo", id = 0},
        {name = "Neon Direito", id = 1}
    },
    neonColours = {
        { name = "Branco", r = 222, g = 222, b = 255},
        { name = "Azul", r = 2, g = 21, b = 255},
        { name = "Azul Elétrico", r = 3, g = 83, b = 255},
        { name = "Verde Menta", r = 0, g = 255, b = 140},
        { name = "Verde Limão", r = 94, g = 255, b = 1},
        { name = "Amarelo", r = 255, g = 255, b = 0},
        { name = "Dourado", r = 255, g = 150, b = 0},
        { name = "Laranja", r = 255, g = 62, b = 0},
        { name = "Vermelho", r = 255, g = 1, b = 1},
        { name = "Rosa Claro", r = 255, g = 50, b = 100},
        { name = "Rosa Pink", r = 255, g = 5, b = 190},
        { name = "Roxo", r = 35, g = 1, b = 255},
        { name = "Luz Negra", r = 15, g = 3, b = 255}
    }
}

-- MAIN COMPONENTS

vehicleCustomisation = {
    {category = "Aerofólio", id = 0},
    {category = "Para-choque Dianteiro", id = 1},
    {category = "Para-choque Traseiro", id = 2},
    {category = "Saia Lateral", id = 3},
    {category = "Escapamento", id = 4},
    {category = "Santo Antônio", id = 5},
    {category = "Grade", id = 6},
    {category = "Capô", id = 7},
    {category = "Paralama Esquerdo", id = 8},
    {category = "Paralama Direito", id = 9},
    {category = "Teto", id = 10},
    {category = "Upgrade do Motor", id = 11},
    {category = "Upgrade dos Freios", id = 12},
    {category = "Upgrade da Transmissão", id = 13},
    {category = "Upgrade da Suspensão", id = 15},
    {category = "Blindagem", id = 16},
    {category = "Turbo", id = 18},
    {category = "Placas", id = 25},
    {category = "Acabamento A", id = 27},
    {category = "Enfeites", id = 28},
    {category = "Painel", id = 29},
    {category = "Mostradores", id = 30},
    {category = "Alto-falante da Porta", id = 31},
    {category = "Bancos", id = 32},
    {category = "Volante", id = 33},
    {category = "Alavanca de Câmbio", id = 34},
    {category = "Placa Decorativa", id = 35},
    {category = "Caixa de Som", id = 36},
    {category = "Porta-malas", id = 37},
    {category = "Hidráulica", id = 38},
    {category = "Bloco do Motor", id = 39},
    {category = "Filtro de Ar", id = 40},
    {category = "Barra de Suspensão", id = 41},
    {category = "Cobertura do Arco", id = 42},
    {category = "Antena", id = 43},
    {category = "Acabamento B", id = 44},
    {category = "Tanque de Combustível", id = 45},
    {category = "Janela", id = 46},
    {category = "Pintura Especial", id = 48},
    {category = "Buzinas", id = 14,
        hornNames = {
            {name = "Buzina Caminhão", id = 0},
            {name = "Buzina Policial", id = 1},
            {name = "Buzina  Palhaço", id = 2},
            {name = "Buzina Musical 1", id = 3},
            {name = "Buzina Musical 2", id = 4},
            {name = "Buzina Musical 3", id = 5},
            {name = "Buzina Musical 4", id = 6},
            {name = "Buzina Musical 5", id = 7},
            {name = "Trombone Triste", id = 8},
            {name = "Buzina Clássica 1", id = 9},
            {name = "Buzina Clássica 2", id = 10},
            {name = "Buzina Clássica 3", id = 11},
            {name = "Buzina Clássica 4", id = 12},
            {name = "Buzina Clássica 5", id = 13},
            {name = "Buzina Clássica 6", id = 14},
            {name = "Buzina Clássica 7", id = 15},
            {name = "Escala - Dó", id = 16},
            {name = "Escala - Ré", id = 17},
            {name = "Escala - Mi", id = 18},
            {name = "Escala - Fá", id = 19},
            {name = "Escala - Sol", id = 20},
            {name = "Escala - Lá", id = 21},
            {name = "Escala - Si", id = 22},
            {name = "Escala - Dó", id = 23},
            {name = "Buzina Jazz 1", id = 24},
            {name = "Buzina Jazz 2", id = 25},
            {name = "Buzina Jazz 3", id = 26},
            {name = "Loop Jazz", id = 27},
            {name = "Hino Americano 1", id = 28},
            {name = "Hino Americano 2", id = 29},
            {name = "Hino Americano 3", id = 30},
            {name = "Hino Americano 4", id = 31},
            {name = "Loop Clássico 8", id = 32},
            {name = "Loop Clássico 9", id = 33},
            {name = "Loop Clássico 10", id = 34},
            {name = "Buzina Clássica 8", id = 35},
            {name = "Buzina Clássica 9", id = 36},
            {name = "Buzina Clássica 10", id = 37},
            {name = "Loop Funeral", id = 38},
            {name = "Funeral", id = 39},
            {name = "Loop Assustador", id = 40},
            {name = "Assustador", id = 41},
            {name = "Loop San Andreas", id = 42},
            {name = "San Andreas", id = 43},
            {name = "Loop Liberty City", id = 44},
            {name = "Liberty City", id = 45},
            {name = "Loop Festivo 1", id = 46},
            {name = "Festivo 1", id = 47},
            {name = "Loop Festivo 2", id = 48},
            {name = "Festivo 2", id = 49},
            {name = "Loop Festivo 3", id = 50},
            {name = "Festivo 3", id = 51}
        }
    }
}

-- COLORS

vehicleResprayOptions = {
    {category = "Clássico", id = 0,
        colours = {
            {name = "Preto", id = 0},
            {name = "Preto Carbono", id = 147},
            {name = "Grafite", id = 1},
            {name = "Preto Antracite", id = 11},
            {name = "Aço Preto", id = 11},
            {name = "Aço Escuro", id = 3},
            {name = "Prata", id = 4},
            {name = "Prata Azulada", id = 5},
            {name = "Aço Laminado", id = 6},
            {name = "Prata Sombria", id = 7},
            {name = "Prata Pedra", id = 8},
            {name = "Prata Meia-Noite", id = 9},
            {name = "Prata Ferro Fundido", id = 10},
            {name = "Vermelho", id = 27},
            {name = "Vermelho Torino", id = 28},
            {name = "Vermelho Fórmula", id = 29},
            {name = "Vermelho Lava", id = 150},
            {name = "Vermelho Chama", id = 30},
            {name = "Vermelho Grace", id = 31},
            {name = "Vermelho Granada", id = 32},
            {name = "Vermelho Pôr do Sol", id = 33},
            {name = "Vermelho Cabernet", id = 34},
            {name = "Vermelho Vinho", id = 143},
            {name = "Vermelho Candy", id = 35},
            {name = "Rosa Pink", id = 135},
            {name = "Rosa Pfister", id = 137},
            {name = "Rosa Salmão", id = 136},
            {name = "Laranja Nascer do Sol", id = 36},
            {name = "Laranja", id = 38},
            {name = "Laranja Brilhante", id = 138},
            {name = "Dourado", id = 99},
            {name = "Bronze", id = 90},
            {name = "Amarelo", id = 88},
            {name = "Amarelo Corrida", id = 89},
            {name = "Amarelo Orvalho", id = 91},
            {name = "Verde Escuro", id = 49},
            {name = "Verde Corrida", id = 50},
            {name = "Verde Mar", id = 51},
            {name = "Verde Oliva", id = 52},
            {name = "Verde Brilhante", id = 53},
            {name = "Verde Gasolina", id = 54},
            {name = "Verde Limão", id = 92},
            {name = "Azul Meia-Noite", id = 141},
            {name = "Azul Galáxia", id = 61},
            {name = "Azul Escuro", id = 62},
            {name = "Azul Saxão", id = 63},
            {name = "Azul", id = 64},
            {name = "Azul Marinheiro", id = 65},
            {name = "Azul Porto", id = 66},
            {name = "Azul Diamante", id = 67},
            {name = "Azul Surf", id = 68},
            {name = "Azul Náutico", id = 69},
            {name = "Azul Corrida", id = 73},
            {name = "Azul Ultra", id = 70},
            {name = "Azul Claro", id = 74},
            {name = "Marrom Chocolate", id = 96},
            {name = "Marrom Bisão", id = 101},
            {name = "Marrom Escuro", id = 95},
            {name = "Marrom Feltzer", id = 94},
            {name = "Marrom Bordo", id = 97},
            {name = "Marrom Faia", id = 103},
            {name = "Marrom Siena", id = 104},
            {name = "Marrom Selado", id = 98},
            {name = "Marrom Musgo", id = 100},
            {name = "Marrom Madeira", id = 102},
            {name = "Marrom Palha", id = 99},
            {name = "Marrom Arenoso", id = 105},
            {name = "Marrom Desbotado", id = 106},
            {name = "Roxo Schafter", id = 71},
            {name = "Roxo Spinnaker", id = 72},
            {name = "Roxo Meia-Noite", id = 142},
            {name = "Roxo Brilhante", id = 145},
            {name = "Creme", id = 107},
            {name = "Branco Gelo", id = 111},
            {name = "Branco Frost", id = 112}
        }
    },
    {category = "Metálico", id = 1,
        colours = {{name = "Black", id = 0},
            {name = "Preto",                   id = 0},
            {name = "Preto Carbono",          id = 147},
            {name = "Grafite",                id = 1},
            {name = "Preto Antracite",        id = 11},
            {name = "Aço Preto",              id = 11},
            {name = "Aço Escuro",             id = 3},
            {name = "Prata",                  id = 4},
            {name = "Prata Azulada",          id = 5},
            {name = "Aço Laminado",           id = 6},
            {name = "Prata Sombria",          id = 7},
            {name = "Prata Pedra",            id = 8},
            {name = "Prata Meia-Noite",       id = 9},
            {name = "Prata Ferro Fundido",    id = 10},
            {name = "Vermelho",               id = 27},
            {name = "Vermelho Torino",        id = 28},
            {name = "Vermelho Fórmula",       id = 29},
            {name = "Vermelho Lava",          id = 150},
            {name = "Vermelho Chama",         id = 30},
            {name = "Vermelho Grace",         id = 31},
            {name = "Vermelho Granada",       id = 32},
            {name = "Vermelho Pôr do Sol",    id = 33},
            {name = "Vermelho Cabernet",      id = 34},
            {name = "Vermelho Vinho",         id = 143},
            {name = "Vermelho Candy",         id = 35},
            {name = "Rosa Pink",              id = 135},
            {name = "Rosa Pfister",           id = 137},
            {name = "Rosa Salmão",            id = 136},
            {name = "Laranja Nascer do Sol",  id = 36},
            {name = "Laranja",                id = 38},
            {name = "Laranja Brilhante",      id = 138},
            {name = "Dourado",                id = 99},
            {name = "Bronze",                 id = 90},
            {name = "Amarelo",                id = 88},
            {name = "Amarelo Corrida",        id = 89},
            {name = "Amarelo Orvalho",        id = 91},
            {name = "Verde Escuro",           id = 49},
            {name = "Verde Corrida",          id = 50},
            {name = "Verde Mar",              id = 51},
            {name = "Verde Oliva",            id = 52},
            {name = "Verde Brilhante",        id = 53},
            {name = "Verde Gasolina",         id = 54},
            {name = "Verde Limão",            id = 92},
            {name = "Azul Meia-Noite",        id = 141},
            {name = "Azul Galáxia",           id = 61},
            {name = "Azul Escuro",            id = 62},
            {name = "Azul Saxão",             id = 63},
            {name = "Azul",                   id = 64},
            {name = "Azul Marinheiro",        id = 65},
            {name = "Azul Porto",             id = 66},
            {name = "Azul Diamante",          id = 67},
            {name = "Azul Surf",              id = 68},
            {name = "Azul Náutico",           id = 69},
            {name = "Azul Corrida",           id = 73},
            {name = "Azul Ultra",             id = 70},
            {name = "Azul Claro",             id = 74},
            {name = "Marrom Chocolate",       id = 96},
            {name = "Marrom Bisão",           id = 101},
            {name = "Marrom Escuro",          id = 95},
            {name = "Marrom Feltzer",         id = 94},
            {name = "Marrom Bordo",           id = 97},
            {name = "Marrom Faia",            id = 103},
            {name = "Marrom Siena",           id = 104},
            {name = "Marrom Selado",          id = 98},
            {name = "Marrom Musgo",           id = 100},
            {name = "Marrom Madeira",         id = 102},
            {name = "Marrom Palha",           id = 99},
            {name = "Marrom Arenoso",         id = 105},
            {name = "Marrom Desbotado",       id = 106},
            {name = "Roxo Schafter",          id = 71},
            {name = "Roxo Spinnaker",         id = 72},
            {name = "Roxo Meia-Noite",        id = 142},
            {name = "Roxo Brilhante",         id = 145},
            {name = "Creme",                  id = 107},
            {name = "Branco Gelo",            id = 111},
            {name = "Branco Frost",           id = 112}
        }
    },
    {category = "Matte", id = 2,
        colours = {{name = "Preto", id = 12},
            {name = "Cinza",             id = 13},
            {name = "Cinza Claro",       id = 14},
            {name = "Branco Gelo",       id = 131},
            {name = "Azul",              id = 83},
            {name = "Azul Escuro",       id = 82},
            {name = "Azul Meia-Noite",   id = 84},
            {name = "Roxo Meia-Noite",   id = 149},
            {name = "Roxo Schafter",     id = 148},
            {name = "Vermelho",          id = 39},
            {name = "Vermelho Escuro",   id = 40},
            {name = "Laranja",           id = 41},
            {name = "Amarelo",           id = 42},
            {name = "Verde Limão",       id = 55},
            {name = "Verde",             id = 128},
            {name = "Verde Floresta",    id = 151},
            {name = "Verde Folhagem",    id = 155},
            {name = "Verde Oliva",       id = 152},
            {name = "Terra Escura",      id = 153},
            {name = "Areia do Deserto",  id = 154}
        }
    },
    {category = "Metals", id = 3,
            colours = {
            {name = "Aço Escovado",          id = 117},
            {name = "Aço Preto Escovado",   id = 118},
            {name = "Alumínio Escovado",    id = 119},
            {name = "Ouro Puro",            id = 158},
            {name = "Ouro Escovado",        id = 159},
            {name = "Cromado",              id = 120}
        }
    }
}
